add: sensitive tag
terraform-ibm-modules/terraform-ibm-code-engine pull request #105
Opened 2024-09-23 11:24 UTC by Aayush-Abhyarthi

### Description

This PR adds sensitive tag to the data variable in the secret submodule.
https://github.ibm.com/GoldenEye/issues/issues/10858

### Release required?

- [X] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

This PR adds sensitive tag to the data variable in the secret submodule.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-09-23 11:24 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-09-23 12:25 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-09-23 12:33 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-09-23 16:38 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-09-23 19:12 UTC, Aayush-Abhyarthi commented
**Reason for skipping the upgrade test** - Making the `data` variable sensitive will update the `resource  "ibm_code_engine_secret" "ce_secret block"`.  But this is not a breaking change. The value of the data variable before and after being marked as `sensitive = true` remains same and no resource is being destroyed.

2024-09-24 08:12 UTC, ocofaigh requested changes
Isn't this also exposed in the root level module too? So we need the changes there too

2024-09-24 08:21 UTC, Aayush-Abhyarthi commented
@ocofaigh  `data` variable is a part of `secrets` variable at the root level. Should I mark the complete `secrets` object as sensitive?

2024-09-24 08:44 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-09-24 09:02 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-09-24 09:09 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-09-24 11:25 UTC, ocofaigh commented
@shemau Could you take a look please? Is it valid to mark all these as sensitive?

2024-09-24 13:25 UTC, shemau commented on outputs.tf
> +  sensitive   = true
This needs checking. AFAIK this is a set of `secret` submodule outputs. I do not believe those are actually a secret, they are a name AND a couple of IDs. It does not contain the value that is the sensitive payload.
This is supported by the fact that the secret submodule does not mark any of the outputs as sensitive.

2024-09-24 13:30 UTC, shemau commented on solutions/apps/outputs.tf
> +  sensitive   = true
This seems misplaced as well. The output is from the secret submodule is not secret.

If anything is going to be sensitive it will be the var.secrets input in variables.tf in the same folder.

2024-09-24 13:31 UTC, shemau commented on main.tf
> +  data       = sensitive(each.value.data)
Arguably this is too late to mark it as sensitive. Should the whole of the for_each (var.secrets) be marked as sensitive in the variables.tf?

2024-09-24 13:33 UTC, shemau commented on examples/apps/outputs.tf
> +  sensitive   = true
Similarly, the output of the secret submodule does not appear to actually contain any sensitive data.

2024-09-24 13:33 UTC, shemau commented on examples/jobs/outputs.tf
> +  sensitive   = true
Similarly, the output of the secret submodule does not appear to actually contain any sensitive data.

2024-09-24 14:46 UTC, Aayush-Abhyarthi commented on examples/jobs/outputs.tf
> +  sensitive   = true
Agreed. Made the changes.

2024-09-24 14:46 UTC, Aayush-Abhyarthi commented on examples/apps/outputs.tf
> +  sensitive   = true
Agreed. Made the changes.

2024-09-24 14:47 UTC, Aayush-Abhyarthi commented on outputs.tf
> +  sensitive   = true
Removed the sensitive tag from the output.

2024-09-24 14:49 UTC, Aayush-Abhyarthi commented on main.tf
> +  data       = sensitive(each.value.data)
On marking the whole `secrets` object as sensitive, it seems to have become non iterable? terraform throwing error - `"Sensitive values, or values derived from sensitive values, cannot be used as for_each arguments. If used, the sensitive value could be exposed as a resource instance key."`.

2024-09-24 14:50 UTC, Aayush-Abhyarthi commented on solutions/apps/outputs.tf
> +  sensitive   = true
removed sensitive tag from output

2024-09-24 15:47 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-09-24 16:14 UTC, shemau commented on main.tf
> +  data       = sensitive(each.value.data)
Indeed, the main review noted: ```If/when the whole object is marked sensitive there would be new restrictions on using ANY part of the object as a for_each block.```

I was concerned that this might happen.

Some experimentation would be required to how to implement this.

2024-09-24 16:20 UTC, Aayush-Abhyarthi commented on main.tf
> +  data       = sensitive(each.value.data)
I think it would be ok to make only the `data` part of the `secrets` variable as sensitive. This won't affect the existing code format much.

2024-09-30 10:59 UTC, shemau commented on main.tf
> +  data       = sensitive(each.value.data)
This should work. There is no reason for terraform to output the whole of the secret object, so marking data when it is used is fine.

2024-09-30 11:00 UTC, shemau approved these changes
LGTM

2024-09-30 11:36 UTC, ocofaigh approved these changes

2024-09-30 11:37 UTC, merged

2024-09-30 11:37 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 2.0.2 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/releases/tag/v2.0.2)
- `v2.0.2`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: