feat:exposed visibility value for the provider in the DA
terraform-ibm-modules/terraform-ibm-code-engine pull request #132
Opened 2024-11-21 13:13 UTC by Aditya-ranjan-16

### Description

exposed [visibility](https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs#visibility) value for the provider in the DAs , with default value set to "private"

[Git issue](https://github.ibm.com/GoldenEye/issues/issues/11337)

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

exposes visibility value for the provider in the DA

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-11-21 13:16 UTC, Aditya-ranjan-16 commented
/run pipeline

2024-11-21 17:02 UTC, Aditya-ranjan-16 commented
/run pipeline

2024-11-22 08:57 UTC, akocbek requested changes

2024-11-22 08:57 UTC, akocbek commented on ibm_catalog.json
> +          },
noticed we do not have all input DA variables defined inside ibm-catalog.json configuration file.
we should sync with other DAs and please add other input variables to `configuration` key inside.

for example redis has all inputs: https://github.com/terraform-ibm-modules/terraform-ibm-icd-redis/blob/7731fa1aebc896c658e034b3a3728d64443cf9f0/ibm_catalog.json#L213

2024-11-22 08:57 UTC, akocbek commented on ibm_catalog.json
> +            },
same here, we need all input variables

2024-11-25 12:19 UTC, Aditya-ranjan-16 commented on ibm_catalog.json
> +            },
added https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/pull/132/commits/455789f8e6a4428bbda8cfc4a30d9124498d6318

2024-11-25 21:01 UTC, ocofaigh commented on ibm_catalog.json
> +            {
same [comment](https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/pull/132/files#r1857340740) as above

2024-11-26 06:00 UTC, Aditya-ranjan-16 commented
/run pipeline

2024-11-26 06:19 UTC, Aditya-ranjan-16 commented on ibm_catalog.json
> +            "options": [
done https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/pull/132/commits/25cda97e4aa758d74d1145f89458e2431242cfe5

2024-11-26 06:20 UTC, Aditya-ranjan-16 commented on ibm_catalog.json
> +            {
done https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/pull/132/commits/25cda97e4aa758d74d1145f89458e2431242cfe5

2024-11-26 09:40 UTC, shemau reviewed
This is neither an approval or a request for changes. The original scope of the issue is growing, so should this be split to a new issue or resolved in this issue?

The description of variables in the apps solution needs some work, and/or a mark down written to explain the 6 compelx variables types in the DA.

There are examples of mark down, eg. ICD Postgresql in solution/standard/DA-types.md.

The lists and maps are fundamentally different things. The lists specifically belong to the app. The maps are other code engine resources. So there may be a hybrid answer from a DA perspective, it may be better to remove the maps from the apps DA and to include new DAs to cover them.

2024-11-26 10:53 UTC, ocofaigh requested changes
Please always explain why upgrade test was skipped. I see no reason why a change like this should need an upgrade test to be skipped.

2024-11-26 10:58 UTC, ocofaigh commented on ibm_catalog.json
> +          },
@shemau we already have a tracking issue for this: https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/issues/63

2024-11-26 10:58 UTC, ocofaigh commented on ibm_catalog.json
> +            "key":"bindings"
we already have a tracking issue for this: https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/issues/63

2024-11-26 10:59 UTC, ocofaigh commented
@shemau There is an issue to write up some supporting docs for the object type inputs: https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/issues/63

I'm going to proceed with merging this PR

2024-11-26 11:00 UTC, ocofaigh approved these changes

2024-11-26 11:00 UTC, merged

2024-11-26 11:01 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 2.1.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/releases/tag/v2.1.0)
- `v2.1.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: