refactor: support creating only one project
terraform-ibm-modules/terraform-ibm-code-engine pull request #146
Opened 2024-12-31 06:04 UTC by Aashiq-J

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-12-31 06:04 UTC, Aashiq-J commented
/run pipeline

2024-12-31 06:29 UTC, Aashiq-J commented
/run pipeline

2024-12-31 06:32 UTC, Aashiq-J commented
/run pipeline

2024-12-31 06:56 UTC, Aashiq-J commented
```
│ Error: Value for undeclared variable
│ 
│ A variable named "project_name" was assigned on the command line, but the
│ root module does not declare a variable of that name. To use this value,
│ add a "variable" block to the configuration.
╵
╷
│ Error: No value for required variable
│ 
│   on variables.tf line 44:
│   44: variable "project_names" {
│ 
│ The root module input variable "project_names" is not set, and has no
│ default value. Use a -var or -var-file command line argument to provide a
│ value for this variable.
╵}
```
will need to skip the upgrade test

2024-12-31 06:56 UTC, Aashiq-J commented
/run pipeline

2025-01-07 04:58 UTC, Aashiq-J commented
/run pipeline

2025-01-07 10:46 UTC, shemau submitted a review, later dismissed
The code looks good to me and IMHO should be merged as is. This will be breaking change for the DA, in that both inputs and outputs are changed (which should be included in the release notes section of the description of the PR), so best to get it in quick.

This only partially addresses the issue, which also requests other code engine project features, all of which are plural and thus require complex inputs and maybe outputs.

2025-01-08 07:46 UTC, Aashiq-J commented
on a second thought, should we add a moved block to prevent at least the first project from being recreated.

2025-01-09 03:11 UTC, Aashiq-J commented
/run pipeline

2025-01-09 03:23 UTC, Aashiq-J commented
/run pipeline

2025-01-13 14:18 UTC, Aashiq-J commented
/run pipeline

2025-01-15 04:49 UTC, Aashiq-J commented
/run pipeline

2025-01-16 13:18 UTC, Aashiq-J commented
/run pipeline

2025-01-24 13:45 UTC, akocbek requested changes
@Aashiq-J small comment

2025-01-24 13:46 UTC, akocbek commented on solutions/project/variables.tf
> +  description = "Prefix to added to all project created by this solution."
typo: `Prefix to added to the project created by this solution.`

2025-01-27 04:15 UTC, Aashiq-J commented
/run pipeline

2025-01-28 05:00 UTC, Aashiq-J commented
/run pipeline

2025-01-28 05:27 UTC, Aashiq-J commented
/run pipeline

2025-01-28 06:24 UTC, Aashiq-J commented
/run pipeline

2025-01-28 09:17 UTC, akocbek approved these changes

2025-01-29 05:05 UTC, Aashiq-J commented
/run pipeline

2025-02-10 16:58 UTC, ocofaigh approved these changes

2025-02-10 17:09 UTC, merged

2025-02-10 17:10 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 3.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/releases/tag/v3.0.0)
- `v3.0.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: