feat: onboard code engine DA to catalog
terraform-ibm-modules/terraform-ibm-code-engine pull request #20
Opened 2024-04-02 13:55 UTC by akocbek

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-04-02 13:56 UTC, akocbek commented on .catalog-onboard-pipeline.yaml
> +    offering_id:
todo: will be added when DA code is merged

2024-04-02 16:12 UTC, SirSpidey requested changes
Overall: 
- fix the product offering name: IBM Cloud Code Engine or Code Engine. 
- pay attention to capitalization. Descriptive nouns like configmaps, domain mapping, bindings, projects, etc. don't get capitalized. 
- Use the product-level feature descriptions to help users understand why they want this (at a glance).

2024-04-02 16:12 UTC, SirSpidey commented on ibm_catalog.json
> +              "descriptions": "This architecture creates IBM Code Engine entities.",
```suggestion
              "descriptions": "This architecture creates IBM Cloud Code Engine entities.",
```

entities is probably not the most understandable term here. Maybe include important stuff from the long_description: `configures the project, apps, domain mappings, secrets, configmaps, and service bindings.`

"Captions can help all users better understand content, but are especially helpful to users of assistive technologies. Draw attention to important features in the diagram."
from https://github.ibm.com/GoldenEye/documentation/blob/master/module-content.md#example-level-properties

2024-04-02 16:12 UTC, SirSpidey commented on ibm_catalog.json
> +              "features": [
for all flavor-level features:
- make sure to call it IBM Cloud Code Engine or Code Engine.
- configmaps: one word in docs. I assume that's correct.

2024-04-02 16:12 UTC, SirSpidey commented on ibm_catalog.json
> +                  "description": "This architecture creates IBM Code Engine entities."
- fix product name 
- diagram.description vs architecture.descriptions: Not sure where the architecture shows up, if at all. But this one under the diagram should probably better match the long_description. 

Also, "Captions can help all users better understand content, but are especially helpful to users of assistive technologies. Draw attention to important features in the diagram."

2024-04-03 11:17 UTC, akocbek commented on ibm_catalog.json
> +        "short_description": "Supports provisioning and configuring IBM Code Engine for IBM Cloud.",
updated

2024-04-03 11:17 UTC, akocbek commented on ibm_catalog.json
> +        "long_description": "This architecture supports creating IBM Code Engine with project, apps, domain mappings, secrets, config maps, and service bindings.",
updated

2024-04-03 11:17 UTC, akocbek commented on ibm_catalog.json
> +        "features": [
updated

2024-04-03 11:17 UTC, akocbek commented on ibm_catalog.json
> +            "description": "Creates service bindings to provide application's access to IBM Cloud services."
- added extra text andwe support application only for now, because ibm provider doesn't support functions yet
- added extra text

2024-04-03 11:17 UTC, akocbek commented on ibm_catalog.json
> +              "descriptions": "This architecture creates IBM Code Engine entities.",
updated text for both

2024-04-03 11:18 UTC, akocbek commented on ibm_catalog.json
> +              "features": [
updated

2024-04-03 13:06 UTC, SirSpidey approved these changes
👍 Looks great. Thanks @akocbek

2024-04-05 09:54 UTC, ocofaigh approved these changes

2024-04-05 09:54 UTC, ocofaigh commented
/run pipeline

2024-04-05 10:02 UTC, merged