Update variables.tf
terraform-ibm-modules/terraform-ibm-code-engine pull request #40
Opened 2024-05-07 20:07 UTC by acolleen

### Description

I've completed a content review and made edits to the `variables.tf` file as part of AHA Epic DAF-303. This review is related to the following issues:

https://github.ibm.com/GoldenEye/issues/issues/7807
https://github.ibm.com/Bluemix/docs/issues/10672

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-05-07 22:25 UTC, shemau approved these changes
LGTM

2024-05-07 22:29 UTC, shemau commented
/run pipeline

2024-05-07 22:31 UTC, shemau commented
No release required. This may fail and need a refresh, since README.md contains variable descriptions.

If it does, I will take a look locally. The branch will need checking out, `pre-commit  run --all-files` run against it and any changes committed.

2024-05-07 23:10 UTC, shemau requested changes
I wonder if some of the changes should also be made to (../../)variables.tf, so that they show up in the README.md for the module as well as on the inputs that will be visible in the catalog module/schematics/projects interfaces.

2024-05-07 23:10 UTC, shemau commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine configmaps to create. For example, `{ configmap_name: {data: {key_1: 'value_1' }}}`.
Lost double quote to terminate description string.

2024-05-07 23:10 UTC, shemau commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine secrets to create. For example, `{ secret_name: {format: 'generic', data: {key_1: 'value_1' }}}`.
Lost double quote to terminate description string.

2024-05-07 23:10 UTC, shemau commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine domain mappings to create. For example, `{ domain_mapping_name: {tls_secret: 'tls_secret_name', components: [{ name : 'app_name', resource_type: 'a
Lost double quote to terminate description string. (before #pragma)

2024-05-07 23:10 UTC, shemau commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine bindings to create. For example, `{ 'PREFIX': {secret_name: 'secret_name', components: [{ name : 'app_name', resource_type: 'app_v2'}]}}`.
Lost double quote to terminate description string.

2024-05-09 18:28 UTC, acolleen commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine configmaps to create. For example, `{ configmap_name: {data: {key_1: 'value_1' }}}`.
I've fixed this issue in the PR.

2024-05-09 18:28 UTC, acolleen commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine secrets to create. For example, `{ secret_name: {format: 'generic', data: {key_1: 'value_1' }}}`.
I've fixed this issue in the PR.

2024-05-09 18:28 UTC, acolleen commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine domain mappings to create. For example, `{ domain_mapping_name: {tls_secret: 'tls_secret_name', components: [{ name : 'app_name', resource_type: 'a
I've fixed this issue in the PR.

2024-05-09 18:28 UTC, acolleen commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine bindings to create. For example, `{ 'PREFIX': {secret_name: 'secret_name', components: [{ name : 'app_name', resource_type: 'app_v2'}]}}`.
I've fixed this issue in the PR.

2024-05-10 15:17 UTC, ocofaigh commented
NOTE: Lets generate a release for this PR so all the Prs I just merged with doc updates are part of a version in the catalog.

2024-05-10 15:58 UTC, akocbek commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine configmaps to create. For example, `{ configmap_name: {data: {key_1: 'value_1' }}}`".
dot `.` should inside double quotation mark
```
}}}`."
```

2024-05-10 15:58 UTC, akocbek commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine secrets to create. For example, `{ secret_name: {format: 'generic', data: {key_1: 'value_1' }}}`".
dot `.` should inside double quotation mark
```
}}}`."
```

2024-05-10 15:58 UTC, akocbek commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine domain mappings to create. For example, `{ domain_mapping_name: {tls_secret: 'tls_secret_name', components: [{ name : 'app_name', resource_type: 'a
dot `.` should inside double quotation mark
```
}}}`."
```

2024-05-10 15:58 UTC, akocbek commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine bindings to create. For example, `{ 'PREFIX': {secret_name: 'secret_name', components: [{ name : 'app_name', resource_type: 'app_v2'}]}}`".
dot `.` should inside double quotation mark
```
}}}`."
```

2024-05-10 15:59 UTC, akocbek requested changes
small typos

2024-05-10 16:04 UTC, acolleen commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine configmaps to create. For example, `{ configmap_name: {data: {key_1: 'value_1' }}}`".
Fixed.

2024-05-10 16:04 UTC, acolleen commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine secrets to create. For example, `{ secret_name: {format: 'generic', data: {key_1: 'value_1' }}}`".
Fixed.

2024-05-10 16:04 UTC, acolleen commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine domain mappings to create. For example, `{ domain_mapping_name: {tls_secret: 'tls_secret_name', components: [{ name : 'app_name', resource_type: 'a
Fixed.

2024-05-10 16:04 UTC, acolleen commented on solutions/apps/variables.tf
> +  description = "A map of the IBM Cloud Code Engine bindings to create. For example, `{ 'PREFIX': {secret_name: 'secret_name', components: [{ name : 'app_name', resource_type: 'app_v2'}]}}`".
Fixed.

2024-05-10 16:12 UTC, akocbek commented
/run pipeline

2024-05-10 16:13 UTC, akocbek commented
/run pipeline

2024-05-10 16:13 UTC, akocbek approved these changes

2024-05-10 16:51 UTC, akocbek commented
/run pipeline

2024-05-13 15:10 UTC, SirSpidey commented
/run pipeline

2024-05-13 17:26 UTC, ocofaigh commented
/run pipeline

2024-05-13 17:52 UTC, ocofaigh approved these changes

2024-05-13 17:53 UTC, merged

2024-05-13 17:53 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.1.6 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/releases/tag/v1.1.6)
- `v1.1.6`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: