feat: add new code engine module
terraform-ibm-modules/terraform-ibm-code-engine pull request #5
Opened 2024-03-06 10:39 UTC by akocbek

- feat: add new code engine module
- feat: add new code engine module

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-03-12 09:08 UTC, akocbek commented
/run pipeline

2024-03-12 09:53 UTC, akocbek commented
/run pipeline

2024-03-12 11:59 UTC, ocofaigh commented
@akocbek can you update code owners file - I propose to add yourself and @shemau as primary and secondary owners.

@shemau would you mind reviewing the PR code please?

2024-03-14 16:31 UTC, akocbek commented
/run pipeline

2024-03-14 16:43 UTC, akocbek commented
/run pipeline

2024-03-20 17:04 UTC, ocofaigh commented on .github/settings.yml
>    topics: terraform, ibm-cloud, terraform-module
please add these topics too: core-team, code-engine, stable, supported

2024-03-21 12:23 UTC, akocbek commented
/run pipeline

2024-03-21 13:23 UTC, ocofaigh commented on README.md
>  ## terraform-ibm-module-template
terraform-ibm-code-engine

2024-03-21 13:24 UTC, ocofaigh commented on README.md
> +source            = "../.."
this isnt properly formatted:
![Uploading image.png…]()

2024-03-21 13:24 UTC, ocofaigh commented on README.md
> +  project_name      = "${var.prefix}-project"
can you use real world like values here instead of `var.`

2024-03-21 14:57 UTC, shemau requested changes
There is a test coverage issue, in that neither binding or domain_mapping are tested anywhere.
These a potentially more complex tests, in that a binding requires a service to bind to, along with a process to generate a service access key. I am not sure about a domain mapping (knowledge gap).

2024-03-21 14:57 UTC, shemau commented on modules/binding/variables.tf
> +  default = []
This is a required property, so this default does not work. I think it should be required.

2024-03-21 14:57 UTC, shemau commented on modules/binding/main.tf
> +    for_each = var.components != null ? var.components : []
Also noted in the variables.tf comment. `component` is a required property, so var.components should never be null and the for_each should never run off the empty list.

2024-03-21 14:57 UTC, shemau commented on modules/domain_mapping/variables.tf
> +  default = []
This is a required property, no default required.

2024-03-21 14:57 UTC, shemau commented on modules/domain_mapping/main.tf
> +    for_each = var.components != null ? var.components : []
This is required, so var.components should not be null and passing an empty list will cause an issue at apply.

2024-03-25 13:18 UTC, akocbek commented
/run pipeline

2024-03-25 13:18 UTC, akocbek commented on modules/domain_mapping/variables.tf
> +  default = []
fixed

2024-03-25 13:18 UTC, akocbek commented on modules/domain_mapping/main.tf
> +    for_each = var.components != null ? var.components : []
fixed

2024-03-25 13:18 UTC, akocbek commented on modules/binding/main.tf
> +    for_each = var.components != null ? var.components : []
fixed

2024-03-25 13:18 UTC, akocbek commented on modules/binding/variables.tf
> +  default = []
fixed

2024-03-25 13:19 UTC, akocbek commented on README.md
> +source            = "../.."
fixed

2024-03-25 13:19 UTC, akocbek commented on README.md
>  ## terraform-ibm-module-template
fixed

2024-03-26 11:30 UTC, akocbek commented
/run pipeline

2024-03-26 16:02 UTC, akocbek commented
/run pipeline

2024-03-26 16:08 UTC, akocbek commented
/run pipeline

2024-03-26 16:15 UTC, akocbek commented
/run pipeline

2024-03-26 16:31 UTC, akocbek commented
/run pipeline

2024-03-27 09:31 UTC, akocbek commented
/run pipeline

2024-03-27 10:02 UTC, akocbek commented
/run pipeline

2024-03-27 10:23 UTC, ocofaigh commented
I haven't reviewed the code (I'll delegate that to @shemau ) however I think it would be better if you had examples named `application` and `job` and just ensure that we have coverage for all features across them (Don't have to add all festures in both). Try keep the examples to a possible real world use case too.

2024-03-27 11:47 UTC, shemau requested changes

2024-03-27 11:47 UTC, shemau commented on README.md
> +This module provisions the IBM Cloud Code Engine fully managed and serverless platform. It supports to deploy containerized workloads, including web apps, batch jobs, builds, config maps, bindings, d
`It supports to deploy` > `It supports deployment of`

2024-03-27 11:47 UTC, shemau commented on examples/basic/main.tf
> +}
@ocofaigh I am unsure what to recommend here. This is a basic example that has a lot of complexity about the public certificate which would be used to create the code engine domain mapping. The pro side of the complexity is that the example is easier to run and creates all the resources. The con is that it distracts from the examples purpose. Rather than the complexity should the three inputs for the data structure just be required properties and drop the preceeding conditional resources/modules?

2024-03-27 11:47 UTC, shemau commented on examples/use-submodule/README.md
> +- Code Engine Apps
use-submodule is an awkward name. Maybe just `modules` or is that more confusing? Maybe custom, or extendable.

2024-03-27 12:25 UTC, akocbek commented
/run pipeline

2024-03-27 12:27 UTC, akocbek commented
/run pipeline

2024-03-27 15:19 UTC, shemau approved these changes
LGTM

2024-03-27 15:21 UTC, merged

2024-03-27 15:22 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: