Ce projects da
terraform-ibm-modules/terraform-ibm-code-engine pull request #92
Opened 2024-08-22 14:32 UTC by daniel-butler-irl

### Description

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-08-22 15:36 UTC, daniel-butler-irl commented
/run pipeline

2024-08-23 14:16 UTC, daniel-butler-irl commented
/run pipeline

2024-08-26 10:05 UTC, daniel-butler-irl commented
/run pipeline

2024-08-26 10:57 UTC, daniel-butler-irl commented
/run pipeline

2024-08-26 11:02 UTC, daniel-butler-irl commented
/run pipeline

2024-08-26 11:39 UTC, daniel-butler-irl commented
/run pipeline

2024-08-26 12:34 UTC, daniel-butler-irl commented
/run pipeline

2024-08-26 15:04 UTC, ocofaigh requested changes
see comments

2024-08-26 15:04 UTC, ocofaigh commented on solutions/projects/catalogValidationValues.json.template
> +  "project_names": [
Ah this syntax is not supported. The variable substitution only works for strings right now. However you should be able to do this and it will add the prefix value to each project name right?

`"project_names": "[\"project1\", \"project2\"]"`

2024-08-26 15:04 UTC, ocofaigh commented on ibm_catalog.json
> +            "label": "New Code Engine Projects",
Projects -> projects (I think @SirSpidey would request that :))

2024-08-26 15:09 UTC, SirSpidey commented on ibm_catalog.json
> +            "label": "New Code Engine Projects",
🥇 for Conall. 
LC projects, as you have at L143

2024-08-26 15:19 UTC, daniel-butler-irl commented on solutions/projects/catalogValidationValues.json.template
> +  "project_names": [
A list of project names is required input. Is there another way of passing the values?

2024-08-26 15:43 UTC, ocofaigh commented on solutions/projects/catalogValidationValues.json.template
> +  "project_names": [
That string will convert to a terraform list when passed to projects / schematics. Just like it does here: https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/blob/8f57dcb83376f81f91e53c8f16557590dc552202/solutions/account-infrastructure-base/catalogValidationValues.json.template#L7

2024-08-26 15:44 UTC, daniel-butler-irl commented
/run pipeline

2024-08-26 17:05 UTC, ocofaigh commented on solutions/projects/catalogValidationValues.json.template
> +  "project_names": [
@daniel-butler-irl you still need to update to `"project_names": "[\"project1\", \"project2\"]"` for this to work

2024-08-26 17:06 UTC, ocofaigh commented on solutions/projects/README.md
> +- A Code Engine projects.
you already mention on line 3 that is creates code engine projects

2024-08-26 17:07 UTC, ocofaigh requested changes
You need to update `.catalog-onboard-pipeline.yaml` and add the new variation to it for catalog pipeline to import it

2024-08-27 08:23 UTC, daniel-butler-irl commented
/run pipeline

2024-08-27 08:56 UTC, ocofaigh commented on .catalog-onboard-pipeline.yaml
> +          region: us-south
you didnt include any compliance section in the ibm_catalog.json so these SCC details will not be used. This means that no SCC scan will be done, and the flavor wont show a compliance tab in the tile. If there is even 1 compliance rule that is applicable to code engine projects, we should probably add a compliance section to the ibm_catalog.json for this flavor, but I’ll create a follow up issue so we don't hold this PR up

2024-08-27 08:58 UTC, ocofaigh commented
@daniel-butler-irl still one items to address: https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/pull/92/files#r1731537672

Also please note this [comment](https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/pull/92#discussion_r1732424113)

2024-08-27 09:06 UTC, daniel-butler-irl commented
/run pipeline

2024-08-27 10:02 UTC, ocofaigh approved these changes
Approving so the new variation can be published. Created 1 follow up issue: https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/issues/95

2024-08-27 10:03 UTC, merged

2024-08-27 10:03 UTC, terraform-ibm-modules-ops commented
:tada: This issue has been resolved in version 1.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-code-engine/releases/tag/v1.2.0)
- `v1.2.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: